# our base image
FROM openjdk:8-jdk-alpine

# copy files required for the app to run
COPY #ni puto caso de momento /usr/src/app/app.py

# tell the port number the container should expose
EXPOSE 8443

# run the application
CMD ["java", "-jar", #ni puto caso de momento "/usr/src/app/app.py"]