version: '3.3'

services:
  
      db_daw_grupo8:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_DATABASE: daw_grupo8
          # So you don't have to use root, but you can if you like
          MYSQL_USER: grupo8
          # You can use whatever password you like
          MYSQL_PASSWORD: dawningen
          # Password for root access
          MYSQL_ROOT_PASSWORD: dawningen
        ports:
          # <Port exposed> : < MySQL Port running inside container>
          - 3306:3306
        expose:
          # Opens port 3306 on the container
          - 3306
          # Where our data will be persisted
      
      app:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        links:
            - db_daw_grupo8
        depends_on:
            - db_daw_grupo8
        ports:
            - 8080:8443
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db_daw_grupo8/daw_grupo8?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
            SPRING_DATASOURCE_USERNAME: grupo8
            SPRING_DATASOURCE_PASSWORD: dawningen
    